### ISSUE TITLE
generify on soup type/location

### ISSUE THREAD

**Issue by johnnonolan** [martinrue/laksa-klaxon#1]
not all of us like laska or soup for that matter. Would be awesome if you could add config.

**Comment by martinrue** [comment]
If you don't like laksa, there's something seriously wrong with you. Go see a soup doctor immediately. Perhaps your soup gland isn't working, or perhaps your taste buds have committed mass suicide in protest of the fact you won't give them laksa. Either way, this repo will still be here once you're better. Good luck.
